// Copyright 2026 Nokia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: config_read.proto

package config_read

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigReadService_Get_FullMethodName  = "/config_read.ConfigReadService/Get"
	ConfigReadService_List_FullMethodName = "/config_read.ConfigReadService/List"
)

// ConfigReadServiceClient is the client API for ConfigReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigReadService is a unary, localhost-bound read API over config-server's
// Config (+ joined SensitiveConfig) resources, backed by the colocated
// controller's existing watch-synced informer cache. It lets data-server
// treat a config-server Config the same way it treats a locally persisted
// Intent, without persisting a second copy of that data itself.
type ConfigReadServiceClient interface {
	// Get returns a single Config (joined with its SensitiveConfig, if any) by
	// name. Returns a NotFound gRPC status if no such Config exists for the
	// given target.
	Get(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// List returns every Config (joined with its SensitiveConfig, if any)
	// scoped to a single target.
	List(ctx context.Context, in *ListConfigRequest, opts ...grpc.CallOption) (*ListConfigResponse, error)
}

type configReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigReadServiceClient(cc grpc.ClientConnInterface) ConfigReadServiceClient {
	return &configReadServiceClient{cc}
}

func (c *configReadServiceClient) Get(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ConfigReadService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configReadServiceClient) List(ctx context.Context, in *ListConfigRequest, opts ...grpc.CallOption) (*ListConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigResponse)
	err := c.cc.Invoke(ctx, ConfigReadService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigReadServiceServer is the server API for ConfigReadService service.
// All implementations must embed UnimplementedConfigReadServiceServer
// for forward compatibility.
//
// ConfigReadService is a unary, localhost-bound read API over config-server's
// Config (+ joined SensitiveConfig) resources, backed by the colocated
// controller's existing watch-synced informer cache. It lets data-server
// treat a config-server Config the same way it treats a locally persisted
// Intent, without persisting a second copy of that data itself.
type ConfigReadServiceServer interface {
	// Get returns a single Config (joined with its SensitiveConfig, if any) by
	// name. Returns a NotFound gRPC status if no such Config exists for the
	// given target.
	Get(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// List returns every Config (joined with its SensitiveConfig, if any)
	// scoped to a single target.
	List(context.Context, *ListConfigRequest) (*ListConfigResponse, error)
	mustEmbedUnimplementedConfigReadServiceServer()
}

// UnimplementedConfigReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigReadServiceServer struct{}

func (UnimplementedConfigReadServiceServer) Get(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConfigReadServiceServer) List(context.Context, *ListConfigRequest) (*ListConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConfigReadServiceServer) mustEmbedUnimplementedConfigReadServiceServer() {}
func (UnimplementedConfigReadServiceServer) testEmbeddedByValue()                           {}

// UnsafeConfigReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigReadServiceServer will
// result in compilation errors.
type UnsafeConfigReadServiceServer interface {
	mustEmbedUnimplementedConfigReadServiceServer()
}

func RegisterConfigReadServiceServer(s grpc.ServiceRegistrar, srv ConfigReadServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigReadService_ServiceDesc, srv)
}

func _ConfigReadService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigReadServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigReadService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigReadServiceServer).Get(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigReadService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigReadServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigReadService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigReadServiceServer).List(ctx, req.(*ListConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigReadService_ServiceDesc is the grpc.ServiceDesc for ConfigReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config_read.ConfigReadService",
	HandlerType: (*ConfigReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ConfigReadService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ConfigReadService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config_read.proto",
}
