// Copyright 2026 Nokia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: config_read.proto

package config_read

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigSnapshotService_Get_FullMethodName    = "/config_read.ConfigSnapshotService/Get"
	ConfigSnapshotService_List_FullMethodName   = "/config_read.ConfigSnapshotService/List"
	ConfigSnapshotService_Modify_FullMethodName = "/config_read.ConfigSnapshotService/Modify"
	ConfigSnapshotService_Delete_FullMethodName = "/config_read.ConfigSnapshotService/Delete"
)

// ConfigSnapshotServiceClient is the client API for ConfigSnapshotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigSnapshotService is a unary, localhost-bound API over config-server's
// TargetSnapshot — the last-applied membership and value for every Intent
// applied to a target, backed by the colocated controller's existing
// watch-synced informer cache for reads. It lets data-server treat a
// config-server Config the same way it treats a locally persisted Intent,
// without persisting a second copy of that data itself, and it lets
// data-server report apply-time results back so TargetSnapshot.Spec.Configs
// stays in sync at the moment southbound apply succeeds (not gated on
// TransactionConfirm).
type ConfigSnapshotServiceClient interface {
	// Get returns a single Config (joined with its SensitiveConfig, if any) by
	// name. Returns a NotFound gRPC status if no such Config exists for the
	// given target.
	Get(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// List returns every Config (joined with its SensitiveConfig, if any)
	// scoped to a single target.
	List(ctx context.Context, in *ListConfigRequest, opts ...grpc.CallOption) (*ListConfigResponse, error)
	// Modify upserts the applied, encrypted payload for a single Intent into
	// TargetSnapshot.Spec.Configs[name]. One call per intent — not batched.
	// This carries the actual applied payload (same shape as ConfigEntry), not
	// a re-read signal.
	Modify(ctx context.Context, in *ModifyConfigRequest, opts ...grpc.CallOption) (*ModifyConfigResponse, error)
	// Delete removes a single Intent's entry from
	// TargetSnapshot.Spec.Configs[name]. One call per intent — not batched.
	// Membership is a single map with no parallel deleted index or tombstone.
	Delete(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
}

type configSnapshotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSnapshotServiceClient(cc grpc.ClientConnInterface) ConfigSnapshotServiceClient {
	return &configSnapshotServiceClient{cc}
}

func (c *configSnapshotServiceClient) Get(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ConfigSnapshotService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configSnapshotServiceClient) List(ctx context.Context, in *ListConfigRequest, opts ...grpc.CallOption) (*ListConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigResponse)
	err := c.cc.Invoke(ctx, ConfigSnapshotService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configSnapshotServiceClient) Modify(ctx context.Context, in *ModifyConfigRequest, opts ...grpc.CallOption) (*ModifyConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyConfigResponse)
	err := c.cc.Invoke(ctx, ConfigSnapshotService_Modify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configSnapshotServiceClient) Delete(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, ConfigSnapshotService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigSnapshotServiceServer is the server API for ConfigSnapshotService service.
// All implementations must embed UnimplementedConfigSnapshotServiceServer
// for forward compatibility.
//
// ConfigSnapshotService is a unary, localhost-bound API over config-server's
// TargetSnapshot — the last-applied membership and value for every Intent
// applied to a target, backed by the colocated controller's existing
// watch-synced informer cache for reads. It lets data-server treat a
// config-server Config the same way it treats a locally persisted Intent,
// without persisting a second copy of that data itself, and it lets
// data-server report apply-time results back so TargetSnapshot.Spec.Configs
// stays in sync at the moment southbound apply succeeds (not gated on
// TransactionConfirm).
type ConfigSnapshotServiceServer interface {
	// Get returns a single Config (joined with its SensitiveConfig, if any) by
	// name. Returns a NotFound gRPC status if no such Config exists for the
	// given target.
	Get(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// List returns every Config (joined with its SensitiveConfig, if any)
	// scoped to a single target.
	List(context.Context, *ListConfigRequest) (*ListConfigResponse, error)
	// Modify upserts the applied, encrypted payload for a single Intent into
	// TargetSnapshot.Spec.Configs[name]. One call per intent — not batched.
	// This carries the actual applied payload (same shape as ConfigEntry), not
	// a re-read signal.
	Modify(context.Context, *ModifyConfigRequest) (*ModifyConfigResponse, error)
	// Delete removes a single Intent's entry from
	// TargetSnapshot.Spec.Configs[name]. One call per intent — not batched.
	// Membership is a single map with no parallel deleted index or tombstone.
	Delete(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	mustEmbedUnimplementedConfigSnapshotServiceServer()
}

// UnimplementedConfigSnapshotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSnapshotServiceServer struct{}

func (UnimplementedConfigSnapshotServiceServer) Get(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConfigSnapshotServiceServer) List(context.Context, *ListConfigRequest) (*ListConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConfigSnapshotServiceServer) Modify(context.Context, *ModifyConfigRequest) (*ModifyConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (UnimplementedConfigSnapshotServiceServer) Delete(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConfigSnapshotServiceServer) mustEmbedUnimplementedConfigSnapshotServiceServer() {}
func (UnimplementedConfigSnapshotServiceServer) testEmbeddedByValue()                               {}

// UnsafeConfigSnapshotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSnapshotServiceServer will
// result in compilation errors.
type UnsafeConfigSnapshotServiceServer interface {
	mustEmbedUnimplementedConfigSnapshotServiceServer()
}

func RegisterConfigSnapshotServiceServer(s grpc.ServiceRegistrar, srv ConfigSnapshotServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigSnapshotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSnapshotService_ServiceDesc, srv)
}

func _ConfigSnapshotService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSnapshotServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSnapshotService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSnapshotServiceServer).Get(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigSnapshotService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSnapshotServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSnapshotService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSnapshotServiceServer).List(ctx, req.(*ListConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigSnapshotService_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSnapshotServiceServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSnapshotService_Modify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSnapshotServiceServer).Modify(ctx, req.(*ModifyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigSnapshotService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSnapshotServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSnapshotService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSnapshotServiceServer).Delete(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigSnapshotService_ServiceDesc is the grpc.ServiceDesc for ConfigSnapshotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSnapshotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config_read.ConfigSnapshotService",
	HandlerType: (*ConfigSnapshotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ConfigSnapshotService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ConfigSnapshotService_List_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _ConfigSnapshotService_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConfigSnapshotService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config_read.proto",
}
