// Copyright 2026 Nokia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: options.proto

package sdcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51301,
		Name:          "sdc.options.secret",
		Tag:           "varint,51301,opt,name=secret",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51302,
		Name:          "sdc.options.secret_field",
		Tag:           "varint,51302,opt,name=secret_field",
		Filename:      "options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Marks every field of the message as a secret, including fields added later.
	// A field opts out with secret_field = false.
	//
	// optional bool secret = 51301;
	E_Secret = &file_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Marks or exempts a single field, wins over secret on the enclosing message.
	//
	// optional bool secret_field = 51302;
	E_SecretField = &file_options_proto_extTypes[1]
)

var File_options_proto protoreflect.FileDescriptor

const file_options_proto_rawDesc = "" +
	"\n" +
	"\roptions.proto\x12\vsdc.options\x1a google/protobuf/descriptor.proto:<\n" +
	"\x06secret\x12\x1f.google.protobuf.MessageOptions\x18\xe5\x90\x03 \x01(\bR\x06secret\x88\x01\x01:E\n" +
	"\fsecret_field\x12\x1d.google.protobuf.FieldOptions\x18\xe6\x90\x03 \x01(\bR\vsecretField\x88\x01\x01B)Z'github.com/sdcio/sdc-protos/sdcpb;sdcpbb\x06proto3"

var file_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
}
var file_options_proto_depIdxs = []int32{
	0, // 0: sdc.options.secret:extendee -> google.protobuf.MessageOptions
	1, // 1: sdc.options.secret_field:extendee -> google.protobuf.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_proto_init() }
func file_options_proto_init() {
	if File_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_proto_rawDesc), len(file_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_options_proto_goTypes,
		DependencyIndexes: file_options_proto_depIdxs,
		ExtensionInfos:    file_options_proto_extTypes,
	}.Build()
	File_options_proto = out.File
	file_options_proto_goTypes = nil
	file_options_proto_depIdxs = nil
}
