// Copyright 2025 Nokia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: tree_persist.proto

package tree_persist

import (
	sdcpb "github.com/sdcio/sdc-protos/sdcpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Intent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	IntentName string                 `protobuf:"bytes,1,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"`
	Root       *TreeElement           `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Priority   int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// depricated
	// bool        deviation                 = 4;
	ExplicitDeletes []*sdcpb.Path `protobuf:"bytes,5,rep,name=explicit_deletes,json=explicitDeletes,proto3" json:"explicit_deletes,omitempty"`
	NonRevertive    bool          `protobuf:"varint,6,opt,name=non_revertive,json=nonRevertive,proto3" json:"non_revertive,omitempty"`
	Orphan          bool          `protobuf:"varint,7,opt,name=orphan,proto3" json:"orphan,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_tree_persist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_tree_persist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_tree_persist_proto_rawDescGZIP(), []int{0}
}

func (x *Intent) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *Intent) GetRoot() *TreeElement {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Intent) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Intent) GetExplicitDeletes() []*sdcpb.Path {
	if x != nil {
		return x.ExplicitDeletes
	}
	return nil
}

func (x *Intent) GetNonRevertive() bool {
	if x != nil {
		return x.NonRevertive
	}
	return false
}

func (x *Intent) GetOrphan() bool {
	if x != nil {
		return x.Orphan
	}
	return false
}

type TreeElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Childs        []*TreeElement         `protobuf:"bytes,4,rep,name=childs,proto3" json:"childs,omitempty"`
	LeafVariant   []byte                 `protobuf:"bytes,5,opt,name=leaf_variant,json=leafVariant,proto3" json:"leaf_variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeElement) Reset() {
	*x = TreeElement{}
	mi := &file_tree_persist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeElement) ProtoMessage() {}

func (x *TreeElement) ProtoReflect() protoreflect.Message {
	mi := &file_tree_persist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeElement.ProtoReflect.Descriptor instead.
func (*TreeElement) Descriptor() ([]byte, []int) {
	return file_tree_persist_proto_rawDescGZIP(), []int{1}
}

func (x *TreeElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreeElement) GetChilds() []*TreeElement {
	if x != nil {
		return x.Childs
	}
	return nil
}

func (x *TreeElement) GetLeafVariant() []byte {
	if x != nil {
		return x.LeafVariant
	}
	return nil
}

var File_tree_persist_proto protoreflect.FileDescriptor

const file_tree_persist_proto_rawDesc = "" +
	"\n" +
	"\x12tree_persist.proto\x12\x12tree_persist.proto\x1a\fschema.proto\"\xf0\x01\n" +
	"\x06Intent\x12\x1f\n" +
	"\vintent_name\x18\x01 \x01(\tR\n" +
	"intentName\x123\n" +
	"\x04root\x18\x02 \x01(\v2\x1f.tree_persist.proto.TreeElementR\x04root\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x127\n" +
	"\x10explicit_deletes\x18\x05 \x03(\v2\f.schema.PathR\x0fexplicitDeletes\x12#\n" +
	"\rnon_revertive\x18\x06 \x01(\bR\fnonRevertive\x12\x16\n" +
	"\x06orphan\x18\a \x01(\bR\x06orphan\"}\n" +
	"\vTreeElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x06childs\x18\x04 \x03(\v2\x1f.tree_persist.proto.TreeElementR\x06childs\x12!\n" +
	"\fleaf_variant\x18\x05 \x01(\fR\vleafVariantB7Z5github.com/sdcio/sdc-protos/tree_persist;tree_persistb\x06proto3"

var (
	file_tree_persist_proto_rawDescOnce sync.Once
	file_tree_persist_proto_rawDescData []byte
)

func file_tree_persist_proto_rawDescGZIP() []byte {
	file_tree_persist_proto_rawDescOnce.Do(func() {
		file_tree_persist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tree_persist_proto_rawDesc), len(file_tree_persist_proto_rawDesc)))
	})
	return file_tree_persist_proto_rawDescData
}

var file_tree_persist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tree_persist_proto_goTypes = []any{
	(*Intent)(nil),      // 0: tree_persist.proto.Intent
	(*TreeElement)(nil), // 1: tree_persist.proto.TreeElement
	(*sdcpb.Path)(nil),  // 2: schema.Path
}
var file_tree_persist_proto_depIdxs = []int32{
	1, // 0: tree_persist.proto.Intent.root:type_name -> tree_persist.proto.TreeElement
	2, // 1: tree_persist.proto.Intent.explicit_deletes:type_name -> schema.Path
	1, // 2: tree_persist.proto.TreeElement.childs:type_name -> tree_persist.proto.TreeElement
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tree_persist_proto_init() }
func file_tree_persist_proto_init() {
	if File_tree_persist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tree_persist_proto_rawDesc), len(file_tree_persist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tree_persist_proto_goTypes,
		DependencyIndexes: file_tree_persist_proto_depIdxs,
		MessageInfos:      file_tree_persist_proto_msgTypes,
	}.Build()
	File_tree_persist_proto = out.File
	file_tree_persist_proto_goTypes = nil
	file_tree_persist_proto_depIdxs = nil
}
